project:
  type: website

website:
  title: "Bouagba Anasse Yahanan"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portofolio"
        file: portofolio.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - icon: github
        href: https://github.com/yahn78
      - icon: LinkedIn
        href: https://www.linkedin.com/in/anasse-yahanan-bouagba-3b39aa242/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

